// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: manage-users.sql

package database

import (
	"context"
	"database/sql"
)

const getUserList = `-- name: GetUserList :many
SELECT subject,
       name,
       username,
       picture,
       email,
       email_verified,
       role,
       updated_at,
       active
FROM users
LIMIT 25 OFFSET ?
`

type GetUserListRow struct {
	Subject       string        `json:"subject"`
	Name          string        `json:"name"`
	Username      string        `json:"username"`
	Picture       interface{}   `json:"picture"`
	Email         string        `json:"email"`
	EmailVerified int64         `json:"email_verified"`
	Role          int64         `json:"role"`
	UpdatedAt     sql.NullTime  `json:"updated_at"`
	Active        sql.NullInt64 `json:"active"`
}

func (q *Queries) GetUserList(ctx context.Context, offset int64) ([]GetUserListRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserList, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserListRow
	for rows.Next() {
		var i GetUserListRow
		if err := rows.Scan(
			&i.Subject,
			&i.Name,
			&i.Username,
			&i.Picture,
			&i.Email,
			&i.EmailVerified,
			&i.Role,
			&i.UpdatedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET active = ?,
    role=?
WHERE subject = ?
`

type UpdateUserRoleParams struct {
	Active  sql.NullInt64 `json:"active"`
	Role    int64         `json:"role"`
	Subject string        `json:"subject"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Active, arg.Role, arg.Subject)
	return err
}

const userEmailExists = `-- name: UserEmailExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = ? AND email_verified = 1)
`

func (q *Queries) UserEmailExists(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userEmailExists, email)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET email_verified = 1
WHERE subject = ?
`

func (q *Queries) VerifyUserEmail(ctx context.Context, subject string) error {
	_, err := q.db.ExecContext(ctx, verifyUserEmail, subject)
	return err
}
