// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type ClientStore struct {
	Subject string        `json:"subject"`
	Name    string        `json:"name"`
	Secret  string        `json:"secret"`
	Domain  string        `json:"domain"`
	Owner   string        `json:"owner"`
	Public  sql.NullInt64 `json:"public"`
	Sso     sql.NullInt64 `json:"sso"`
	Active  sql.NullInt64 `json:"active"`
}

type Otp struct {
	Subject string `json:"subject"`
	Secret  string `json:"secret"`
	Digits  int64  `json:"digits"`
}

type User struct {
	Subject       string        `json:"subject"`
	Name          string        `json:"name"`
	Username      string        `json:"username"`
	Password      string        `json:"password"`
	Picture       interface{}   `json:"picture"`
	Website       interface{}   `json:"website"`
	Email         string        `json:"email"`
	EmailVerified int64         `json:"email_verified"`
	Pronouns      interface{}   `json:"pronouns"`
	Birthdate     sql.NullTime  `json:"birthdate"`
	Zoneinfo      interface{}   `json:"zoneinfo"`
	Locale        interface{}   `json:"locale"`
	Role          int64         `json:"role"`
	UpdatedAt     sql.NullTime  `json:"updated_at"`
	Registered    sql.NullInt64 `json:"registered"`
	Active        sql.NullInt64 `json:"active"`
}
