// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/1f349/tulip/database/types"
	"github.com/1f349/tulip/password"
)

type ClientStore struct {
	Subject string `json:"subject"`
	Name    string `json:"name"`
	Secret  string `json:"secret"`
	Domain  string `json:"domain"`
	Owner   string `json:"owner"`
	Public  bool   `json:"public"`
	Sso     bool   `json:"sso"`
	Active  bool   `json:"active"`
}

type Otp struct {
	Subject string `json:"subject"`
	Secret  string `json:"secret"`
	Digits  int64  `json:"digits"`
}

type User struct {
	Subject       string              `json:"subject"`
	Name          string              `json:"name"`
	Username      string              `json:"username"`
	Password      password.HashString `json:"password"`
	Picture       string              `json:"picture"`
	Website       string              `json:"website"`
	Email         string              `json:"email"`
	EmailVerified bool                `json:"email_verified"`
	Pronouns      types.UserPronoun   `json:"pronouns"`
	Birthdate     sql.NullTime        `json:"birthdate"`
	Zoneinfo      types.UserZone      `json:"zoneinfo"`
	Locale        types.UserLocale    `json:"locale"`
	Role          types.UserRole      `json:"role"`
	UpdatedAt     time.Time           `json:"updated_at"`
	Registered    time.Time           `json:"registered"`
	Active        bool                `json:"active"`
}
